name: proj-turnover
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.24
  - pandas=1.5
  - polars=0.19
  - seaborn=0.12
  - matplotlib=3.7.0
  - google-colab
  - openpyxl
  - jupyterlab
